# fly.toml app configuration file generated for fushigiehon-ai-dry-smoke-7372 on 2024-08-20T09:18:17+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '{app_name}'
primary_region = 'nrt'

[build]
  dockerfile = './Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
